### ISSUE TITLE
LVE,EME,FVE

### ISSUE THREAD

**Issue by ljijj** [wangxuanx/Face-Diffusion-Model#1]
Thank you for your work.

While implementing your work, I noticed that there is no code provided for calculating the LVE, EME, and FVE metrics. Could you please provide the code for these metrics?

I would be very grateful!

**Comment by wangxuanx** [comment]
Thank you for your attention to our work. For the calculation of metrics, I have added metric/metric.py to the project. This file can be used to calculate the above metrics.

**Comment by ljijj** [comment]
I have noted that #1 has been marked as completed. Thank you for the update.







---Original---
From: "wang ***@***.***&gt;
Date: Thu, Nov 21, 2024 17:05 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [wangxuanx/Face-Diffusion-Model] LVE,EME,FVE (Issue #1)




 
Closed #1 as completed.
