### ISSUE TITLE
Demo code and pretrained models

### ISSUE THREAD

**Issue by galib360** [wangxuanx/Face-Diffusion-Model#2]
Hi, Thank you for open sourcing your codebase.

In your **demo/demo_3d_mead.py** script, your arguments for the pretrained models are- 

    parser.add_argument("--stage1_model_path", type=str, default="3D_MEAD/3d_mead_stage1.mpt", help='path of the stage 1 pretrained models')
    parser.add_argument("--stage2_model_path", type=str, default="3D_MEAD/3d_mead_stage2.mpt", help='path of the stage 2 pretrained models')

However, your google drive for pretrained models has only one model for 3DMEAD- **MEAD_model.pth** 

Am I missing something?

**Comment by wangxuanx** [comment]
Thanks for your interest in our work, we have re-uploaded the weights and compressed the two-stage model into a zip file, you can get these pre-trained weights on [this](https://pan.baidu.com/s/1yvWTLXukWKk_dAYfdM917w?pwd=7z8a). We have also updated the link in the homepage, good luck with your research!

**Comment by galib360** [comment]
Thanks for the quick response!
